In [13]:
import cv2
import pandas
import tensorflow
import numpy
import torchvision
import torchvision.transforms as transforms
import torch
import numpy as np
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import random
from matplotlib import pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import keras


In [14]:
image_name_iterator = 0;
image_tensors = [];
real_labels = pandas.DataFrame();
row_index = 0;
torch.backends.cudnn.benchmark = True

In [15]:
def row_to_tensor(row):
    pixels = np.array([]);
    for i in row:
        pixels = np.append(pixels, i);
    image_tensors.append(torch.tensor(pixels));
    return row;
def normalization(df):
    df_min_max_scaled = df.copy() 
  
    for column in df_min_max_scaled.columns: 
        df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())     
    
    return df_min_max_scaled;





In [16]:
data = pandas.read_csv("train.csv");

#data = data.head();

display(data);

#data = data.head();
labels = pandas.DataFrame();
labels['l'] = data['label'];
data.drop(columns=['label'], inplace=True);

for i in range(10):
    real_labels.insert(i, str(i), np.zeros(42000));




display(labels);

#display(data);
#data = data.apply(row_to_tensor, axis=1);
#print(image_tensors);
#plt.show();

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

l
0      1
1      0
2      1
3      4
4      0
...   ..
41995  0
41996  1
41997  7
41998  6
41999  9

[42000 rows x 1 columns]

In [17]:
display(labels);

l
0      1
1      0
2      1
3      4
4      0
...   ..
41995  0
41996  1
41997  7
41998  6
41999  9

[42000 rows x 1 columns]

In [18]:
it = 0;

real_labels['0'] = labels['l'].apply(lambda x: 1 if x == 0 else 0);
real_labels['1'] = labels['l'].apply(lambda x: 1 if x == 1 else 0);
real_labels['2'] = labels['l'].apply(lambda x: 1 if x == 2 else 0);
real_labels['3'] = labels['l'].apply(lambda x: 1 if x == 3 else 0);
real_labels['4'] = labels['l'].apply(lambda x: 1 if x == 4 else 0);
real_labels['5'] = labels['l'].apply(lambda x: 1 if x == 5 else 0);
real_labels['6'] = labels['l'].apply(lambda x: 1 if x == 6 else 0);
real_labels['7'] = labels['l'].apply(lambda x: 1 if x == 7 else 0);
real_labels['8'] = labels['l'].apply(lambda x: 1 if x == 8 else 0);
real_labels['9'] = labels['l'].apply(lambda x: 1 if x == 9 else 0);

display(real_labels);

0  1  2  3  4  5  6  7  8  9
0      0  1  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  1  0  0  0  0  0  0  0  0
3      0  0  0  0  1  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0
...   .. .. .. .. .. .. .. .. .. ..
41995  1  0  0  0  0  0  0  0  0  0
41996  0  1  0  0  0  0  0  0  0  0
41997  0  0  0  0  0  0  0  1  0  0
41998  0  0  0  0  0  0  1  0  0  0
41999  0  0  0  0  0  0  0  0  0  1

[42000 rows x 10 columns]

In [19]:
np.random.seed(0)
random.seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.manual_seed(0)


In [20]:
device = torch.device("mps")
print(device)

mps


In [21]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [22]:
real_labels_2 = pandas.DataFrame();
labels_2 = pandas.DataFrame();
labels_2['l'] = y_train;

real_labels_2['0'] = labels_2['l'].apply(lambda x: 1 if x == 0 else 0);
real_labels_2['1'] = labels_2['l'].apply(lambda x: 1 if x == 1 else 0);
real_labels_2['2'] = labels_2['l'].apply(lambda x: 1 if x == 2 else 0);
real_labels_2['3'] = labels_2['l'].apply(lambda x: 1 if x == 3 else 0);
real_labels_2['4'] = labels_2['l'].apply(lambda x: 1 if x == 4 else 0);
real_labels_2['5'] = labels_2['l'].apply(lambda x: 1 if x == 5 else 0);
real_labels_2['6'] = labels_2['l'].apply(lambda x: 1 if x == 6 else 0);
real_labels_2['7'] = labels_2['l'].apply(lambda x: 1 if x == 7 else 0);
real_labels_2['8'] = labels_2['l'].apply(lambda x: 1 if x == 8 else 0);
real_labels_2['9'] = labels_2['l'].apply(lambda x: 1 if x == 9 else 0);

In [23]:
display(labels_2);
display(real_labels_2);

l
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

0  1  2  3  4  5  6  7  8  9
0      0  0  0  0  0  1  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  0  0  0  1  0  0  0  0  0
3      0  1  0  0  0  0  0  0  0  0
4      0  0  0  0  0  0  0  0  0  1
...   .. .. .. .. .. .. .. .. .. ..
59995  0  0  0  0  0  0  0  0  1  0
59996  0  0  0  1  0  0  0  0  0  0
59997  0  0  0  0  0  1  0  0  0  0
59998  0  0  0  0  0  0  1  0  0  0
59999  0  0  0  0  0  0  0  0  1  0

[60000 rows x 10 columns]

In [24]:


device = torch.device("mps")
print(device)

# load the dataset, split into input (X) and output (y) variables
dataset = data;


X = data.to_numpy();
y = real_labels.to_numpy();
print(X);
#y = np.append(y, real_labels_2.to_numpy());
'''
for it in range(len(x_train)):
    if(it % 100 == 0): print((it / 60000) * 100);
    listt = np.array([], dtype=int);
    for i in range(len(x_train[it])):
        for j in range(len(x_train[it][i])):
            listt = np.append(listt, x_train[it][i][j]);
    #print(listt);
    X = np.append(X, listt);
    if(it == 1000): break;
'''
#print(x_train);
#X = np.append(X, x_train);
#y = np.append(y, y_train);
X = X.reshape((-1, 784))
print(X);


X_tensor = torch.tensor(X, dtype=torch.float32).to(device)
y_tensor = torch.tensor(y, dtype=torch.float32).to(device)
print(X_tensor);
print(y_tensor);



mps
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='mps:0')
tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='mps:0')


In [25]:

# define the model
model = nn.Sequential(
    nn.Linear(784, 1200),
    nn.ReLU(),
    nn.Linear(1200, 1200),
    nn.ReLU(),
    nn.Linear(1200, 10),
    nn.ReLU()
)
model.to(device);
print(model)

# train the model
loss_fn   = nn.L1Loss()  # binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.00000001)

n_epochs = 2000
batch_size = 500

for epoch in range(n_epochs):
    for i in range(0, len(X_tensor), batch_size):
        #if(i % 8000 == 0): 
            #print(i / len(X_tensor) * 100, '% epoch', epoch);
            #for param in model.parameters():
            #    print(param.data)
        Xbatch = X_tensor[i:i+batch_size].to(device)
        #print(Xbatch.shape);
        y_pred = model(Xbatch).to(device);
        ybatch = y_tensor[i:i+batch_size].to(device);
        #print(y_pred);
        #print(y_tensor);
        #print("model.co: ", model.parameters());
        loss = loss_fn(y_pred, ybatch).to(device);
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    if(epoch % 20 == 0): print(f'Finished epoch {epoch}, latest loss {loss}')

# compute accuracy (no_grad is optional)

Sequential(
  (0): Linear(in_features=784, out_features=1200, bias=True)
  (1): ReLU()
  (2): Linear(in_features=1200, out_features=1200, bias=True)
  (3): ReLU()
  (4): Linear(in_features=1200, out_features=10, bias=True)
  (5): ReLU()
)
Finished epoch 0, latest loss 3.8096492290496826
Finished epoch 20, latest loss 2.902545928955078
Finished epoch 40, latest loss 2.112333059310913
Finished epoch 60, latest loss 1.4582850933074951
Finished epoch 80, latest loss 0.9618209004402161
Finished epoch 100, latest loss 0.6189600229263306
Finished epoch 120, latest loss 0.3980945348739624
Finished epoch 140, latest loss 0.2590100169181824
Finished epoch 160, latest loss 0.18243078887462616
Finished epoch 180, latest loss 0.14206689596176147
Finished epoch 200, latest loss 0.12060321867465973
Finished epoch 220, latest loss 0.11034079641103745


KeyboardInterrupt: 

In [ ]:
with torch.no_grad():
    y_pred = model(X_tensor).to(device);
    y_pred.to(device);
print(y_pred);
print(y_tensor)
accuracy = (y_pred.round() == y)
print(f"Accuracy {accuracy}")

In [ ]:
test = pandas.read_csv("test1.csv");

arr = test.to_numpy();

print(arr);

X_test_tensor = torch.tensor(arr, dtype=torch.float32).to(device);

print(X_test_tensor);

print(model(X_test_tensor))

In [ ]:
pandas.set_option('display.max_columns', None)

mat = model(X_test_tensor).cpu().data.numpy();
print(len(mat));

ans = pandas.DataFrame();

file = open("ansGPU.csv", 'w');

for i in range(len(mat)):
    mx = mat[i].argmax();
    file.write(str(i + 1) + ',' + str(mx) + "\n");
    #print("i: ", i, " mx:", mx)
    
